App:
  Environment: "dev"
  Id: "DNS-ASSESSMENT"
kafka:
  Brokers: ["localhost:9092"]
  TopicsConsumer: ["security-assessment"]
  TopicsProducer: ["security-assessment"]
  TopicsError: ["security-assessment-error"]
  GroupID: "security-assessment-ingestion-group"
